package ast.lineaP;

public enum KindAsig{
	ASIG, SUMAPREF, RESTAPREF, MULTIPREF, DIVIPREF, MODPREF, DIVENTPREF, ACCESO, POINTER, DOLLAR, EXCLAM, AND, OR, CORCH, PARE, LLAVE, POR, DIVENT, MOD, DIV, MAS, MENOS, MAYOR, MENOR, MAYORIG, MENORIG, IGUALIG, DISTINTO, TOFLOAT, TOINT, LLAMADA, BOOL, CONST, DINAMICA, ENT, REAL, UNITARIO;
}