
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Sun May 19 20:34:36 CEST 2024
//----------------------------------------------------

package constructorast;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int DOSPUNTOS = 12;
  public static final int DISTINTO = 22;
  public static final int DIVENT = 8;
  public static final int POR = 6;
  public static final int MULTIPREF = 25;
  public static final int PCIERRE = 48;
  public static final int LLAVECIE = 50;
  public static final int EXCLAM = 15;
  public static final int RIAL = 2;
  public static final int RESTAPREF = 24;
  public static final int PUNTOCOMA = 66;
  public static final int REG = 40;
  public static final int REF = 41;
  public static final int FOR = 37;
  public static final int DELETE = 43;
  public static final int AND = 16;
  public static final int WRITERIAL = 59;
  public static final int FUN = 36;
  public static final int READNUM = 56;
  public static final int OR = 17;
  public static final int BOOL = 31;
  public static final int DIV = 7;
  public static final int NUM = 3;
  public static final int TYPEDEF = 54;
  public static final int LOOP = 39;
  public static final int MODPREF = 27;
  public static final int WRITENUM = 57;
  public static final int MAIN = 45;
  public static final int IF = 34;
  public static final int FACT = 63;
  public static final int DIVENTPREF = 28;
  public static final int WRITEBOOL = 61;
  public static final int EOF = 0;
  public static final int RETURN = 46;
  public static final int ASIG = 13;
  public static final int NEW = 42;
  public static final int error = 1;
  public static final int MENOS = 5;
  public static final int MENOR = 11;
  public static final int MOD = 9;
  public static final int VOID = 44;
  public static final int TOINT = 52;
  public static final int REAL = 65;
  public static final int MAYOR = 10;
  public static final int ENT = 62;
  public static final int PAP = 47;
  public static final int READRIAL = 58;
  public static final int ELSE = 35;
  public static final int CORCHETECIERRE = 30;
  public static final int MAYORIG = 19;
  public static final int SUMAPREF = 23;
  public static final int IDEN = 55;
  public static final int TOFLOAT = 51;
  public static final int WHILE = 38;
  public static final int DOLLAR = 18;
  public static final int LIST = 33;
  public static final int ACCESO = 14;
  public static final int INFACT = 64;
  public static final int MENORIG = 20;
  public static final int CORCHETEAP = 29;
  public static final int READBOOL = 60;
  public static final int LLAVEAP = 49;
  public static final int IGUALIG = 21;
  public static final int AS = 53;
  public static final int POINTER = 32;
  public static final int MAS = 4;
  public static final int DIVIPREF = 26;
}

